import type { Metadata } from 'next';
import { inter } from '@/config/fonts';

import Providers from '@/lib/Providers';
import GradiantBlob from '@/components/ui/GradiantBlob';
import { cn } from '@/utils/utils';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen antialiased', inter.className)}>
        <Providers>
          <GradiantBlob />

          {children}
        </Providers>
      </body>
    </html>
  );
}
