export const bookGenres = [
  'Fiction',
  'Non-fiction',
  'Mystery',
  'Thriller',
  'Science Fiction',
  'Fantasy',
  'Romance',
  'Horror',
  'Historical Fiction',
  'Biography',
  'Autobiography',
  'Self-help',
  'Business',
  'Science',
  'Travel',
  'Poetry',
  'Children',
  'Young Adult',
  'Graphic Novels',
  'Cookbooks',
  'Religion',
  'Philosophy',
  'Art',
  'History',
  'Classics',
  'Humor',
  'Drama',
  'Adventure',
  'Crime',
  'Comics',
  'Manga',
  'Western',
  'Short Stories',
  'Essays',
  'Satire',
  'Anthology',
  'Dystopian',
] as const;
